import { products as seededProducts } from "../lib/fixtures.ts"
import { isExportableAttributeField } from "../lib/demo-contract.ts"
import type {
  CandidateRecord,
  ContractFieldId,
  EvidenceRecord,
  ExportPreview,
  ProductRecord,
  ResearchJob,
  ReviewDecision,
} from "../lib/types.ts"

type ReviewDecisionRecord = {
  id: string
  candidateId: string
  decision: ReviewDecision
  reason?: string
  createdAt: string
}

type DemoCatalogState = {
  products: ProductRecord[]
  researchRuns: Map<string, ResearchJob>
  reviewDecisions: ReviewDecisionRecord[]
}

const demoState: DemoCatalogState = {
  products: structuredClone(seededProducts),
  researchRuns: new Map<string, ResearchJob>(),
  reviewDecisions: [],
}

function now() {
  return new Date().toISOString()
}

export function listStoredProducts() {
  return demoState.products
}

export function getStoredProduct(productId: string) {
  return demoState.products.find((item) => item.id === productId) ?? null
}

function getLatestAcceptedCandidates(candidates: CandidateRecord[]) {
  const byField = new Map<ContractFieldId, CandidateRecord>()

  for (const candidate of candidates) {
    if (candidate.status !== "accepted") continue
    byField.set(candidate.fieldName, candidate)
  }

  return [...byField.values()]
}

export function buildExportPreview(product: ProductRecord): ExportPreview {
  const rows = getLatestAcceptedCandidates(product.candidates).reduce<ExportPreview["rows"]>((acc, candidate) => {
    if (!isExportableAttributeField(candidate.fieldName)) return acc
    acc.push({
      field: candidate.fieldName,
      value: candidate.candidateValue,
      evidenceIds: candidate.sourceEvidenceIds,
    })
    return acc
  }, [])

  return {
    productId: product.id,
    miraklProductId: product.miraklProductId,
    status: "DRAFT_PREVIEW_ONLY",
    rows,
    safetyMessage: "Preview only; no Mirakl export file has been generated or submitted.",
  }
}

export function applyReviewDecisionToProduct(product: ProductRecord, candidateId: string, decision: ReviewDecision, reason?: string) {
  const candidate = product.candidates.find((item) => item.id === candidateId)
  if (!candidate) return null

  if (decision === "APPROVE") {
    for (const sibling of product.candidates) {
      if (sibling.id !== candidateId && sibling.fieldName === candidate.fieldName && sibling.status === "accepted") {
        sibling.status = "rejected"
        sibling.reason = "Superseded by a newer accepted candidate."
      }
    }
  }

  candidate.status = decision === "APPROVE" ? "accepted" : decision === "REJECT" ? "rejected" : "needs_evidence"
  if (reason) candidate.reason = reason
  return candidate
}

export function createMockResearchRun(productId: string) {
  const product = getStoredProduct(productId)
  if (!product) return null

  const sequence = demoState.researchRuns.size + 1
  const runId = `mock-research-${product.id}-${sequence}`
  const evidenceId = `ev-research-${product.id}-${sequence}`
  const candidateId = `cand-research-${product.id}-${sequence}`
  const timestamp = now()

  const evidence: EvidenceRecord = {
    id: evidenceId,
    productId: product.id,
    aggregatorId: "internal-reference",
    sourceName: "Internal reference library",
    sourceType: "internal_reference",
    title: `${product.title} demo research note`,
    summary: "Mock research added a demo-safe reference note without changing the Mirakl baseline.",
    extractedFields: {
      researchSummary: "Research completed in preview mode",
    },
    capturedAt: timestamp,
    confidence: "medium",
  }

  const candidate: CandidateRecord = {
    id: candidateId,
    productId: product.id,
    fieldName: "researchSummary",
    currentValue: null,
    candidateValue: `Research job ${runId} produced additional demo evidence for ${product.title}.`,
    confidence: "medium",
    status: "proposed",
    sourceEvidenceIds: [evidence.id],
    reason: "Generated by the preview-mode research workflow.",
  }

  product.evidence.push(evidence)
  product.candidates.push(candidate)

  const run: ResearchJob = {
    id: runId,
    productId,
    status: "SUCCEEDED",
    runner: "mock-opencode-lightweb",
    createdAt: timestamp,
    updatedAt: timestamp,
    summary: "Mock research completed. No Mirakl writes were performed.",
    evidenceIds: [evidence.id],
    candidateIds: [candidate.id],
  }

  demoState.researchRuns.set(runId, run)
  return run
}

export function getResearchRun(id: string) {
  return demoState.researchRuns.get(id) ?? null
}

export function findCandidate(candidateId: string) {
  for (const product of demoState.products) {
    const candidate = product.candidates.find((item) => item.id === candidateId)
    if (candidate) return { product, candidate }
  }
  return null
}

export function addReviewDecision(candidateId: string, decision: ReviewDecision, reason?: string) {
  const found = findCandidate(candidateId)
  if (!found) return null

  const updatedCandidate = applyReviewDecisionToProduct(found.product, candidateId, decision, reason)
  if (!updatedCandidate) return null

  const record: ReviewDecisionRecord = {
    id: `review-${demoState.reviewDecisions.length + 1}`,
    candidateId,
    decision,
    reason,
    createdAt: now(),
  }

  demoState.reviewDecisions.push(record)
  return record
}

export function exportPreview(productId: string) {
  const product = getStoredProduct(productId)
  if (!product) return null
  return buildExportPreview(product)
}
