import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs"
import path from "node:path"
import { products as seededProducts } from "../lib/fixtures.ts"
import { isExportableAttributeField } from "../lib/demo-contract.ts"
import type {
  CandidateRecord,
  ContractFieldId,
  EvidenceRecord,
  ExportPreview,
  ProductRecord,
  ResearchJob,
  ResearchJobStatus,
  ReviewDecision,
} from "../lib/types.ts"

type ReviewDecisionRecord = {
  id: string
  candidateId: string
  decision: ReviewDecision
  reason?: string
  createdAt: string
}

type StoredResearchJob = ResearchJob & {
  applied: boolean
}

type DemoCatalogState = {
  products: ProductRecord[]
  researchRuns: StoredResearchJob[]
  reviewDecisions: ReviewDecisionRecord[]
}

const stateFilePath = path.join(process.cwd(), "data", "demo-state.json")

function now() {
  return new Date().toISOString()
}

function toMillis(value: string) {
  return new Date(value).getTime()
}

function buildInitialState(): DemoCatalogState {
  return {
    products: structuredClone(seededProducts),
    researchRuns: [],
    reviewDecisions: [],
  }
}

function ensureStateFile() {
  mkdirSync(path.dirname(stateFilePath), { recursive: true })
  try {
    readFileSync(stateFilePath, "utf8")
  } catch {
    writeFileSync(stateFilePath, JSON.stringify(buildInitialState(), null, 2))
  }
}

function readState(): DemoCatalogState {
  ensureStateFile()
  return JSON.parse(readFileSync(stateFilePath, "utf8")) as DemoCatalogState
}

function writeState(state: DemoCatalogState) {
  const tempFilePath = `${stateFilePath}.tmp`
  writeFileSync(tempFilePath, JSON.stringify(state, null, 2))
  renameSync(tempFilePath, stateFilePath)
}

export function resetDemoState() {
  writeState(buildInitialState())
}

export function listStoredProducts() {
  return readState().products
}

export function getStoredProduct(productId: string) {
  return readState().products.find((item) => item.id === productId) ?? null
}

function getLatestAcceptedCandidates(candidates: CandidateRecord[]) {
  const byField = new Map<ContractFieldId, CandidateRecord>()

  for (const candidate of candidates) {
    if (candidate.status !== "accepted") continue
    byField.set(candidate.fieldName, candidate)
  }

  return [...byField.values()]
}

export function buildExportPreview(product: ProductRecord): ExportPreview {
  const rows = getLatestAcceptedCandidates(product.candidates).reduce<ExportPreview["rows"]>((acc, candidate) => {
    if (!isExportableAttributeField(candidate.fieldName)) return acc
    acc.push({
      field: candidate.fieldName,
      value: candidate.candidateValue,
      evidenceIds: candidate.sourceEvidenceIds,
    })
    return acc
  }, [])

  return {
    productId: product.id,
    miraklProductId: product.miraklProductId,
    status: "DRAFT_PREVIEW_ONLY",
    rows,
    safetyMessage: "Preview only; no Mirakl export file has been generated or submitted.",
  }
}

export function applyReviewDecisionToProduct(product: ProductRecord, candidateId: string, decision: ReviewDecision, reason?: string) {
  const candidate = product.candidates.find((item) => item.id === candidateId)
  if (!candidate) return null

  if (decision === "APPROVE") {
    for (const sibling of product.candidates) {
      if (sibling.id !== candidateId && sibling.fieldName === candidate.fieldName && sibling.status === "accepted") {
        sibling.status = "rejected"
        sibling.reason = "Superseded by a newer accepted candidate."
      }
    }
  }

  candidate.status = decision === "APPROVE" ? "accepted" : decision === "REJECT" ? "rejected" : "needs_evidence"
  if (reason) candidate.reason = reason

  product.listingStatus = product.candidates.some((item) => item.status === "accepted")
    ? "EXPORT_PREVIEW_AVAILABLE"
    : "READY_FOR_REVIEW"

  return candidate
}

function buildResearchOutcome(product: ProductRecord, sequence: number, timestamp: string) {
  const evidence: EvidenceRecord = {
    id: `ev-research-${product.id}-${sequence}`,
    productId: product.id,
    aggregatorId: "spec-database",
    sourceName: "Specification database",
    sourceType: "spec_database",
    sourceUrl: "https://specs.example/freeclip-2",
    title: `${product.title} technical field refresh`,
    summary: "Mock research validated battery technology and microphone support while keeping the Mirakl baseline unchanged.",
    extractedFields: {
      microphone: "Dual microphone call pickup",
      batteryTechnology: "Li-Ion",
      researchSummary: "Research completed; review the new technical findings before export.",
    },
    capturedAt: timestamp,
    confidence: "high",
  }

  const candidate: CandidateRecord = {
    id: `cand-research-${product.id}-${sequence}`,
    productId: product.id,
    fieldName: "microphone",
    currentValue: null,
    candidateValue: "Dual microphone call pickup",
    confidence: "high",
    status: "proposed",
    sourceEvidenceIds: [evidence.id],
    reason: "Generated by the preview-mode research workflow.",
  }

  return { evidence, candidate }
}

function applyResearchOutcome(state: DemoCatalogState, run: StoredResearchJob, timestamp: string) {
  const product = state.products.find((item) => item.id === run.productId)
  if (!product || run.applied) return run

  const { evidence, candidate } = buildResearchOutcome(product, state.researchRuns.length, timestamp)
  product.evidence.push(evidence)
  product.candidates.push(candidate)
  product.bestEvidenceByField.microphone = candidate.candidateValue
  product.listingStatus = "READY_FOR_REVIEW"
  product.warnings = [
    ...product.warnings.filter((warning) => warning !== "Candidate EAN differs from Mirakl baseline"),
    "Research completed; new candidate values are ready for review",
  ]

  run.evidenceIds = [evidence.id]
  run.candidateIds = [candidate.id]
  run.summary = "Mock research completed. New candidate values are ready for review."
  run.updatedAt = timestamp
  run.applied = true
  return run
}

function deriveResearchStatus(run: StoredResearchJob, currentTime: string): ResearchJobStatus {
  const elapsedMs = toMillis(currentTime) - toMillis(run.createdAt)
  if (elapsedMs < 1000) return "QUEUED"
  if (elapsedMs < 2500) return "RUNNING"
  return "SUCCEEDED"
}

export function createMockResearchRun(productId: string) {
  const state = readState()
  const product = state.products.find((item) => item.id === productId)
  if (!product) return null

  const existing = state.researchRuns.find((run) => run.productId === productId && run.status !== "SUCCEEDED")
  if (existing) return existing

  const sequence = state.researchRuns.length + 1
  const timestamp = now()
  const run: StoredResearchJob = {
    id: `mock-research-${product.id}-${sequence}`,
    productId,
    status: "QUEUED",
    runner: "mock-opencode-lightweb",
    createdAt: timestamp,
    updatedAt: timestamp,
    summary: "Mock research queued. No Mirakl writes are performed.",
    evidenceIds: [],
    candidateIds: [],
    applied: false,
  }

  product.listingStatus = "RESEARCH_IN_PROGRESS"
  state.researchRuns.push(run)
  writeState(state)
  return run
}

export function getResearchRun(id: string, currentTime = now()) {
  const state = readState()
  const run = state.researchRuns.find((item) => item.id === id)
  if (!run) return null

  const nextStatus = deriveResearchStatus(run, currentTime)
  run.status = nextStatus

  if (nextStatus === "SUCCEEDED") {
    applyResearchOutcome(state, run, currentTime)
  } else {
    run.updatedAt = currentTime
  }

  writeState(state)
  return run
}

export function findCandidate(candidateId: string) {
  const state = readState()
  for (const product of state.products) {
    const candidate = product.candidates.find((item) => item.id === candidateId)
    if (candidate) return { state, product, candidate }
  }
  return null
}

export function addReviewDecision(candidateId: string, decision: ReviewDecision, reason?: string) {
  const found = findCandidate(candidateId)
  if (!found) return null

  const updatedCandidate = applyReviewDecisionToProduct(found.product, candidateId, decision, reason)
  if (!updatedCandidate) return null

  const record: ReviewDecisionRecord = {
    id: `review-${found.state.reviewDecisions.length + 1}`,
    candidateId,
    decision,
    reason,
    createdAt: now(),
  }

  found.state.reviewDecisions.push(record)
  writeState(found.state)
  return record
}

export function exportPreview(productId: string) {
  const state = readState()
  const product = state.products.find((item) => item.id === productId)
  if (!product) return null
  return buildExportPreview(product)
}
